version: '3.8'

services:

  backend: 
    build: ./services/backend
    ports:
      - 5000:5000 
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 5000
    environment:
      - DATABASE_URL=postgresql+psycopg2://usr:1234@db:5432/mydb
    depends_on:
      - db
      
  ml: 
    build: ./services/ml
    ports:
      - 4000:4000 
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 4000
    environment:
      - DATABASE_URL=postgresql+psycopg2://usr:1234@db:5432/mydb
    depends_on:
      - db
      
  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - './app/node_modules'
    ports:
      - 8080:8080
  
  db:
    image: postgres:13
    expose:
      - 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb 

      
volumes:
  postgres_data: